[package]
edition = "2018"
name = "spl"
version = "0.1.0"
authors = ["Peter Schmidt-Nielsen <schmidtnielsenpeter@gmail.com>"]

[build-dependencies]
lalrpop = ">= 0.16.0"

[dependencies]
lalrpop-util = ">= 0.16.0"
regex = ">= 1.0.5"

[lib]
name = "spl"
path = "spl.rs"
